# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZWQxYzY4OWMwMjUyYzYyYjUxMzAyMzAyYTM2MmRjMzIyOTk5N2JkYjI4YTZkODUwNTAyYTAzM2NjNWUzOWFkYjljOTM4MDAxMmVlMGIxMTY5MDllMWQ1NmQ2ZjBjNDkwYjMzNjgwNzcyZjNhNmU3NGEyMDA1ZmE4NzAyMzgwMjE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
